[package]
edition = "2021"
name = "todo"
version = "0.1.0"

[dependencies]
colored = "2.0.4"
home = "0.5.5"
serde_json = "1.0.107"
structopt = "0.3.26"

[dependencies.serde]
version = "1.0.190"
features = ["derive"]
